---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.15
    volumes:
      - ./kuma/data:/app/data
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/hosts:/etc/hosts:ro
    ports:
      - 3001:3001
    restart: unless-stopped
