---
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-secret
  namespace: flux-system
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: 'https://discord.com/api/webhooks/1348142750821908581/N3ZWwc_KtZVALO2gkuKMvoa0E_p5hDV6BHrJfwBIdlE-ES9m9mp0xBjYq-3v4OybQP_N'
