---
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-secret
  namespace: flux-system
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: 
    valueFrom:
      secretKeyRef:
        name: discord-webhook-url
        key: DISCORD_WEBHOOK_URL
