extends: default

rules:
  indentation:
    spaces: 2
    indent-sequences: false
    level: error

  line-length:
    max: 160
    level: warning

  trailing-spaces:
    level: error

  new-line-at-end-of-file:
    level: warning

  truthy:
    level: error

  document-start:
    level: warning

  key-duplicates:
    level: error

  brackets:
    level: warning