---
# Loki config
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
    final_sleep: 0s
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h

storage_config:
  filesystem:
    directory: /loki

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

limits_config:
  retention_period: 720h  # 30 days
  max_cache_freshness_per_query: 10m

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 days
