global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: uptime-kuma
    static_configs:
      - targets: ['uptime-kuma:3001']

  - job_name: podinfo
    static_configs:
      - targets: ['podinfo.local']

  - job_name: flux
    static_configs:
      - targets: ['flux-source.local']
