global:
  scrape_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: grafana
    static_configs:
      - targets: ['grafana:3000']

  - job_name: podinfo
    static_configs:
      - targets: ['podinfo.local']

  - job_name: flux
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - flux-system
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: flux
    metrics_path: /metrics
    scheme: http

