---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: 34.4.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    crds:
      enabled: true
    ingressRoute:
      dashboard:
        enabled: true
    service:
      type: LoadBalancer
      loadBalancerIP:
        valueFrom:
          secretKeyRef:
            name: traefik-external-ip
            key: EXTERNAL_IP
    ports:
      web:
        port: 80
      websecure:
        enabled: false
