---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- notifications/discord-provider.yaml
- notifications/discord-webhook-secret.yaml
- notifications/flux-alert.yaml
