apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flux-source-metrics
  namespace: flux-system
spec:
  entryPoints:
    - web
  routes: 
    - match: "Host(`flux-source.local`) && Path(`/metrics`)"
      kind: Rule
      services:
        - name: source-controller
          port: 80