---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      version: 34.4.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik-system
  interval: 1h
  values:
    service:
      type: NodePort
    ports:
      web:
        nodePort: 30080
      websecure:
        enabled: false

