---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  values:
    service:
      type: NodePort
    ports:
      web:
        nodePort: 30080
      websecure:
        enabled: false

